void find_number (int a[10][10])
{
    int i,j,c;
    for(i=0;i<10;i++)
    {
        for(j=0;j<10;j++)
        {
            if(a[i][j]!=9)
            {
            c=0;
            if(a[i+1][j+1]==9)
                c++;
            if(a[i][j+1]==9)
                c++;
                if(a[i+1][j]==9)
                c++;
                if(i-1>=0)
                {
                    if(a[i-1][j]==9)
                c++;
                    if(a[i-1][j+1]==9)
                c++;
                }
                if(j-1>0)
                {
                    if(a[i][j-1]==9)
                c++;
                    if(a[i+1][j-1]==9)
                c++;
                }
                if((i-1>=0)&&(j-1>=0))
                {
                    if(a[i-1][j-1]==9)
                c++;
                }
                a[i][j]=c;
            }
        }
    }
}
